regions:
    path: /api/geozones/{level}/{_locale}
    controller: MyPrm\GeoZones\Infrastructure\Http\Controller\GeoZonesController
    methods: 'GET'
    defaults:
        _locale: en

sub-regions:
    path: /api/geozones/{level}/{_locale}
    controller: MyPrm\GeoZones\Infrastructure\Http\Controller\GeoZonesController
    methods: 'GET'
    defaults:
        _locale: en

test:
    path: /api/test
    controller: MyPrm\GeoZones\Infrastructure\Http\Controller\TestController
    methods: 'GET'